map $http_authorization $ollama_api_authorized {
    default 0;
    "Bearer 316339f148c24563b44ab23c73696df9" 1;
}

limit_req_zone $binary_remote_addr zone=ollama_api:10m rate=2r/s;
limit_conn_zone $binary_remote_addr zone=ollama_conn:10m;