# HTTP redirects for subdomain hosts — redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name nextcloud.tdemers.duckdns.org
                pihole.tdemers.duckdns.org
                netdata.tdemers.duckdns.org
                vaultwarden.tdemers.duckdns.org
                copilot.tdemers.duckdns.org;
    return 301 https://$host$request_uri;
}
